"""Add Expense model with belongs-to-user relationship

Revision ID: 984991a9f9c9
Revises: cd6c2afd9d4a
Create Date: 2026-08-04 07:31:04.104783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984991a9f9c9'
down_revision = 'cd6c2afd9d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
